USE DATABASE CORTEX_ANALYST_SEMANTICS;
USE SCHEMA SEMANTIC_MODEL_GENERATOR;

CREATE OR REPLACE NETWORK RULE looker_rule
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('<% looker_url %>');

CREATE OR REPLACE SECRET looker_client_secret
  TYPE = GENERIC_STRING
  SECRET_STRING = '<% client_secret %>';

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION looker_access_int
  ALLOWED_NETWORK_RULES = (looker_rule)
  ALLOWED_AUTHENTICATION_SECRETS = (looker_client_secret)
  ENABLED = TRUE;

GRANT READ ON SECRET looker_client_secret TO ROLE <% streamlit_role %>;
GRANT USAGE ON INTEGRATION looker_access_int TO ROLE <% streamlit_role %>;

USE ROLE <% streamlit_role %>;

ALTER STREAMLIT CORTEX_ANALYST_SEMANTICS.SEMANTIC_MODEL_GENERATOR.SEMANTIC_MODEL_GENERATOR
  SET EXTERNAL_ACCESS_INTEGRATIONS = (looker_access_int)
  SECRETS = ('looker_client_secret' = CORTEX_ANALYST_SEMANTICS.SEMANTIC_MODEL_GENERATOR.looker_client_secret);